version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: event-booking-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=event_booking_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - event-booking-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: event-booking-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/event_booking_db?authSource=admin
      - JWT_SECRET=mySecretKey123456789012345678901234567890
      - CORS_ALLOWED_ORIGINS=http://localhost:4200,http://frontend:4200
    depends_on:
      - mongodb
    networks:
      - event-booking-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: event-booking-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    environment:
      - API_BASE_URL=http://backend:8080/api
    depends_on:
      - backend
    networks:
      - event-booking-network

volumes:
  mongodb_data:

networks:
  event-booking-network:
    driver: bridge